/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../pages/__root";
import { Route as IndexRouteImport } from "./../pages/index";
import { Route as AgendaRouteImport } from "./../pages/agenda";
import { Route as GrupoConfiguracoesRouteImport } from "./../pages/grupo.configuracoes";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AgendaRoute = AgendaRouteImport.update({
  id: "/agenda",
  path: "/agenda",
  getParentRoute: () => rootRouteImport,
} as any);
const GrupoConfiguracoesRoute = GrupoConfiguracoesRouteImport.update({
  id: "/grupo/configuracoes",
  path: "/grupo/configuracoes",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/agenda": typeof AgendaRoute;
  "/grupo/configuracoes": typeof GrupoConfiguracoesRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/agenda": typeof AgendaRoute;
  "/grupo/configuracoes": typeof GrupoConfiguracoesRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/agenda": typeof AgendaRoute;
  "/grupo/configuracoes": typeof GrupoConfiguracoesRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/agenda" | "/grupo/configuracoes";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/agenda" | "/grupo/configuracoes";
  id: "__root__" | "/" | "/agenda" | "/grupo/configuracoes";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AgendaRoute: typeof AgendaRoute;
  GrupoConfiguracoesRoute: typeof GrupoConfiguracoesRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agenda": {
      id: "/agenda";
      path: "/agenda";
      fullPath: "/agenda";
      preLoaderRoute: typeof AgendaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/grupo/configuracoes": {
      id: "/grupo/configuracoes";
      path: "/grupo/configuracoes";
      fullPath: "/grupo/configuracoes";
      preLoaderRoute: typeof GrupoConfiguracoesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  GrupoConfiguracoesRoute: GrupoConfiguracoesRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
